/**
 * 110+ Star Metadata & Five Element Color Mapping (TuViVietnam.vn Standard)
 */

import { StarType } from '../types/chart.types';

export interface StarMetaItem {
  element: string;
  type: StarType;
}

export const STAR_METADATA: Record<string, StarMetaItem> = {
  // 14 Chính Tinh
  'Tử Vi': { element: 'Thổ', type: 'Major' },
  'Thiên Cơ': { element: 'Mộc', type: 'Major' },
  'Thái Dương': { element: 'Hỏa', type: 'Major' },
  'Vũ Khúc': { element: 'Kim', type: 'Major' },
  'Thiên Đồng': { element: 'Thủy', type: 'Major' },
  'Liêm Trinh': { element: 'Hỏa', type: 'Major' },
  'Thiên Phủ': { element: 'Thổ', type: 'Major' },
  'Thái Âm': { element: 'Thủy', type: 'Major' },
  'Tham Lang': { element: 'Thủy', type: 'Major' },
  'Cự Môn': { element: 'Thủy', type: 'Major' },
  'Thiên Tướng': { element: 'Thủy', type: 'Major' },
  'Thiên Lương': { element: 'Mộc', type: 'Major' },
  'Thất Sát': { element: 'Kim', type: 'Major' },
  'Phá Quân': { element: 'Thủy', type: 'Major' },

  // Cát Tinh / Trợ Tinh / Tứ Hóa
  'Tả Phù': { element: 'Thổ', type: 'Good' },
  'Hữu Bật': { element: 'Thủy', type: 'Good' },
  'Văn Xương': { element: 'Kim', type: 'Good' },
  'Văn Khúc': { element: 'Thủy', type: 'Good' },
  'Thiên Khôi': { element: 'Hỏa', type: 'Good' },
  'Thiên Việt': { element: 'Hỏa', type: 'Good' },
  'Hóa Lộc': { element: 'Mộc', type: 'TuHoa' },
  'Hóa Quyền': { element: 'Mộc', type: 'TuHoa' },
  'Hóa Khoa': { element: 'Mộc', type: 'TuHoa' },
  'Hóa Kỵ': { element: 'Thủy', type: 'Bad' },
  'Ân Quang': { element: 'Mộc', type: 'Good' },
  'Thiên Quý': { element: 'Thổ', type: 'Good' },
  'Tam Thai': { element: 'Thủy', type: 'Good' },
  'Bát Tọa': { element: 'Mộc', type: 'Good' },
  'Phong Cáo': { element: 'Thổ', type: 'Good' },
  'Thai Phụ': { element: 'Kim', type: 'Good' },
  'Quốc Ấn': { element: 'Thổ', type: 'Good' },
  'Đường Phù': { element: 'Mộc', type: 'Good' },
  'Thiên Quan': { element: 'Hỏa', type: 'Good' },
  'Thiên Phúc': { element: 'Thổ', type: 'Good' },
  'Long Trì': { element: 'Thủy', type: 'Good' },
  'Phượng Các': { element: 'Mộc', type: 'Good' },
  'Giải Thần': { element: 'Mộc', type: 'Good' },
  'Thiên Giải': { element: 'Hỏa', type: 'Good' },
  'Địa Giải': { element: 'Thổ', type: 'Good' },
  'Đào Hoa': { element: 'Mộc', type: 'Good' },
  'Hồng Loan': { element: 'Thủy', type: 'Good' },
  'Thiên Hỷ': { element: 'Thủy', type: 'Good' },
  'Thiên Mã': { element: 'Hỏa', type: 'Good' },
  'Hoa Cái': { element: 'Kim', type: 'Good' },
  'Thiên Trù': { element: 'Thổ', type: 'Good' },
  'Nguyệt Đức': { element: 'Hỏa', type: 'Good' },
  'Thiên Đức': { element: 'Hỏa', type: 'Good' },
  'Bác Sĩ': { element: 'Thủy', type: 'Good' },
  'Bác Sỹ': { element: 'Thủy', type: 'Good' },
  'Lực Sĩ': { element: 'Hỏa', type: 'Good' },
  'Thanh Long': { element: 'Thủy', type: 'Good' },
  'Tướng Quân': { element: 'Mộc', type: 'Good' },
  'Tấu Thư': { element: 'Kim', type: 'Good' },
  'Hỷ Thần': { element: 'Hỏa', type: 'Good' },
  'Lộc Tồn': { element: 'Thổ', type: 'Good' },
  'Thiếu Dương': { element: 'Hỏa', type: 'Good' },
  'Thiếu Âm': { element: 'Thủy', type: 'Good' },
  'Long Đức': { element: 'Thủy', type: 'Good' },
  'Phúc Đức': { element: 'Thổ', type: 'Good' },
  'LN Văn Tinh': { element: 'Kim', type: 'Good' },
  'Thiên Thọ': { element: 'Thổ', type: 'Good' },
  'Thiên Tài': { element: 'Thổ', type: 'Good' },

  // Sát Tinh / Hung Tinh / Bại Tinh
  'Kình Dương': { element: 'Kim', type: 'Bad' },
  'Đà La': { element: 'Kim', type: 'Bad' },
  'Hỏa Tinh': { element: 'Hỏa', type: 'Bad' },
  'Linh Tinh': { element: 'Hỏa', type: 'Bad' },
  'Địa Không': { element: 'Hỏa', type: 'Bad' },
  'Địa Kiếp': { element: 'Hỏa', type: 'Bad' },
  'Tang Môn': { element: 'Mộc', type: 'Bad' },
  'Bạch Hổ': { element: 'Kim', type: 'Bad' },
  'Thiên Khốc': { element: 'Kim', type: 'Bad' },
  'Thiên Hư': { element: 'Thủy', type: 'Bad' },
  'Tiểu Hao': { element: 'Hỏa', type: 'Bad' },
  'Đại Hao': { element: 'Hỏa', type: 'Bad' },
  'Phi Liêm': { element: 'Hỏa', type: 'Bad' },
  'Bệnh Phù': { element: 'Thổ', type: 'Bad' },
  'Phục Binh': { element: 'Hỏa', type: 'Bad' },
  'Quan Phủ': { element: 'Hỏa', type: 'Bad' },
  'Quan Phù': { element: 'Hỏa', type: 'Bad' },
  'Thái Tuế': { element: 'Hỏa', type: 'Bad' },
  'Tử Phù': { element: 'Hỏa', type: 'Bad' },
  'Tuế Phá': { element: 'Hỏa', type: 'Bad' },
  'Điếu Khách': { element: 'Hỏa', type: 'Bad' },
  'Trực Phù': { element: 'Hỏa', type: 'Bad' },
  'Cô Thần': { element: 'Thổ', type: 'Bad' },
  'Quả Tú': { element: 'Thổ', type: 'Bad' },
  'Kiếp Sát': { element: 'Hỏa', type: 'Bad' },
  'Phá Toái': { element: 'Hỏa', type: 'Bad' },
  'Thiên Diêu': { element: 'Thủy', type: 'Bad' },
  'Thiên Y': { element: 'Thủy', type: 'Good' },
  'Thiên Hình': { element: 'Hỏa', type: 'Bad' },
  'Thiên Thương': { element: 'Thổ', type: 'Bad' },
  'Thiên Sứ': { element: 'Thủy', type: 'Bad' },
  'Thiên La': { element: 'Kim', type: 'Bad' },
  'Địa Võng': { element: 'Kim', type: 'Bad' },
  'Lưu Hà': { element: 'Thủy', type: 'Bad' },
  'Thiên Không': { element: 'Hỏa', type: 'Bad' },
  'Đẩu Quân': { element: 'Hỏa', type: 'Bad' },

  // Sao Lưu
  'L.Thái Tuế': { element: 'Hỏa', type: 'Luu' },
  'L.Lộc Tồn': { element: 'Thổ', type: 'Luu' },
  'L.Kình Dương': { element: 'Kim', type: 'Luu' },
  'L.Đà La': { element: 'Kim', type: 'Luu' },
  'L.Tang Môn': { element: 'Mộc', type: 'Luu' },
  'L.Bạch Hổ': { element: 'Kim', type: 'Luu' },
  'L.Tuế Phá': { element: 'Hỏa', type: 'Luu' },
  'L.Thiên Mã': { element: 'Hỏa', type: 'Luu' },
  'L.Thiên Khốc': { element: 'Kim', type: 'Luu' },
  'L.Thiên Hư': { element: 'Thủy', type: 'Luu' },
  'L.Thiên Khôi': { element: 'Hỏa', type: 'Luu' },
  'L.Thiên Việt': { element: 'Kim', type: 'Luu' }
};
